# Generated by Django 3.2.4 on 2021-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_description_contact_message_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
